export const SELECT_TEXT = 'SELECT_TEXT'

export const ADD_MARK = 'ADD_MARK'
export const ADD_MARK_SUCCESS = 'ADD_MARK_SUCCESS'
export const ADD_MARK_FAILURE = 'ADD_MARK_FAILURE'

export const NEW_NOTE = 'SHOW_COMMENT_VIEW'

export const FETCH_COMMENTS = 'FETCH_COMMENTS'
export const FETCH_COMMENT_SUCCESSS = 'FETCH_COMMENT_SUCCESSS'
export const FETCH_COMMENT_FAILURES = 'FETCH_COMMENT_FAILURES'

export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'

export const CHANGE_OPTION_STATUS = 'CHANGE_OPTION_STATUS'

